name: template-package

on:
  push:
  workflow_call:

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create Hello World Python package
        run: |
          mkdir hello_world_package
          echo "def hello():\n    print('Hello, world!')" > hello_world_package/__init__.py
          echo "[metadata]\nname = hello_world_package\nversion = 0.0.1" > setup.cfg
          echo "from setuptools import setup; setup()" > setup.py

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish package
        run: |
          python -m pip install twine
          python -m twine upload --repository-url https://nuget.pkg.github.com/timothywarner --skip-existing dist/*
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
