name: template-artifact

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Runner Hostname and IP
      run: |
        echo "Runner Hostname: $(hostname)"
        curl http://ipinfo.io/ip

    - name: Create cert.txt
      run: echo "Certificate Content" > cert.txt

    - name: Zip the cert.txt
      run: zip cert.zip cert.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cert.zip
        path: cert.zip
